import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Results'
import request from '../utils/request'

export default function Home({results}) {
  // console.log(props);
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <Header></Header>
      <Navbar></Navbar>
      <Results results={results}></Results>
     
    </div>
  )
}



export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const req = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}`)
  .then((res) => res.json());

  return {
    props: {
      results: req.results
    }
  }

}